// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package main.ru.hse.java.proto;

public interface QueryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Query)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>required int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>required int32 size = 2;</code>
   */
  boolean hasSize();
  /**
   * <code>required int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>repeated int32 num = 3;</code>
   */
  java.util.List<java.lang.Integer> getNumList();
  /**
   * <code>repeated int32 num = 3;</code>
   */
  int getNumCount();
  /**
   * <code>repeated int32 num = 3;</code>
   */
  int getNum(int index);
}
